-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg7SlRwCqIMMQ451nK
rcztWWte2gVux4+UbGhRdoYry9SgCgYIKoZIzj0DAQehRANCAATqprJbk60Ky5FR
whGVWNMkMv5seHGVjCuFcjz7bHC9sYgnDxNqvLEXJzlnWFnGeVYZ09DofcJ6+uwJ
coA5guYV
-----END PRIVATE KEY-----